dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: iwIe4wv0E6xGyCqcwCzBDx+sp4FFnp3R4LJ7V/lkhunnRu6iwHAUNEwerqFBpPatllzqatKoZaCq4EPruW3ebCkbjOFDXsmOCdCpaCsRvBUG8QzKH3Z/HqoYVu6JitSetQyFDr9qdFTVYset4gGrXajbELtiotZ3UMD2EnYZd04IrGDqHml2BjEfiICMHZ9R0ytmhrpUJ1bySODBK9DKXT6PIsRs6M6QhZby2UAoKTDYM8YG5EfUicXDm5FWdbLpRR+iTL+qwwJ4BNpr84NOLAy/CqSIhRwI/I+BWlgPXdgPgbK8Ho7v3HqIEtKxCmZAq44RwUYngEm504Oqp9e1zSzMw30aT8+5knvoEN925ajFyE3CjRfNkueNJ88myrEsD5j8QCrGqL5gZiMquSVovBbgpZqADPduvAe5/2DtKgFX/nDHcYcIfBbDmBDoOupVx2oPp49CyjTUrSagja8LTZVdhXg4+ze8Zx2bq9nAtUpNQdqsZjYaLo2xHiFW/85kQrwxMADaWrpIX1M1tpgz0uIOE0uamrF0K474NUQCqlJQ3p/IR4lpBat8JWdeXwdHaPCCVgu1aWzVQ47wMUBe2EXgiAH6TPJT0xHufDOa0oEPBhoN8IZfdtk1va+fg+AvNw/XF+3icdQGQMsKnUPevZNaKNbitPSlbA6JvVH7iOU=
env:
  global:
    secure: MEjfk+Lqx04bEe577urmj3/6BFWb+29K4sIuCd063QzNdS46AKFUojLHtD+U9IZgDiJFggwYVLUvwnfe0tEAjaWU7wO7kIV1BB1fnP7TA/PG8SHAdwocJTUMGmwuEK0W8VzrjpdtR2HNzV8nVoecmFc+9l93G+eRXyqh8B4N6zgGC7uRuF4V+6RM9LGJsQ4DGoZ5GdZFPBZrYxCGlXrFNPzCIJ/mwhVDqwxe0qZIQr9KYcaeXm9tXSt/MOFacv4qg0oXX8p51gHYdSL5Bg8DdtAD31+ByXg0BsbN5EnADfVmKuSdo4zrQUbEDQKba0GNX6SJRlAs7If2lZz5rYE2Z+MRKKJO2t/XxWWv6GFTR0SfyYlg8gIIahbM5w4fgGvJqUlxiEvlo2XB3TDO4kyYv5lpJReTSWqfemhvnt1dnmZuXkf+KUOGsuYLrvXewAa/ZG5e9zij2f5jqU7OzUSncKz0xPG0AG682xWKY5M2XNL3LPSq9814s4kC3Y6PUqMhbNDqqLkfw2iiHVtSkrPWOiI+yyTXtKamm01dqB6cLqlQyCsifvap8QRd9ZBgwyPFDn9x1GY0OfL8eTN+E4uvS4TmY4R+tsMvwnXbghtdY05HGuhB4fWKImb6bJ0KuVmlHY1p3btuD54T0+Ed+ljJfYoN9M3Z8atfyQXK5Ehc2uM=
