dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: BI0c/EjXHeVtHBJ7F9lDUVrC3AumTeTR7obrAHImRlvgSCCWgwsyQhRR1OBTGZyGDcRV98Jhwi0MgH++WcYl8zaOKZod/YTXY0ZOalgmoguv7KKEz7uMSHrlLaguxmEPP2/QYT6Ua3ACJa3TUDp4sMpZoY80YKMCxDzaz3nZ3a8edEolBB7BmF63lMIiInM31AVsr2u1f4XSVGCXX7V8DOB3bQdRMklr+HwH+ojHRhCLTbOZceHXm08eJWxmEoCnCaS78SYRr/ZAl8PYPrEVuZCcxN9eDe/9gzksZOrQK+lLR6E68sp39cz25PtjuVk7v6fbXosxae84g0eguCIaW5amKmJ0wr4ATdLIuaNpjVoLPVHWwfZ6jy9LKtFxTt7VLnElY0HtH3TPcZDi3XGbIGACnmcWrB8PXWsqNUbN6c+QhRrr5zDyYz8eqqQC3FTFFmZDNrunwC7fAkrmL+9bB7uaWyfzwGJbJhFxg/SQroZKHxxUwkkvxIE+DJu8UfrK20avc7FhbU0et7osG002QwU/smo7eJqwO6MUMTwiTvGuXkOQ4va8CfMgflmMKITAC38O2sU2zAOIDYXUbTWEMvlxVxkRrwsDjLBuGsyn8zJbN7ZhU9i0LF4TiVwE415ZAsZPVjlUsrw52b7kvOGZ8syTkyhB5pWl0gGJYZsZeGw=

notifications:
  slack:
    rooms:
      secure: YHWBJkRuOe6zHVhiL+8IHoA6wWMK0yXRw9nXUkMoipnamwQt9l4uPRWaNRS16V2g77y8TLhuNXeww1EFAEMrCqlw2qIPBcgHhEds+1da35URB24BhYDGNHBUL+b4dOVO6QVGjvbVQV193LdU7EYWKuXg1WQ14+TdbCUJnN1KfOj30/M6/77wUjg8RiSTFlKwhWPS3sdJQi1nIyHNq1MNtB1ZVyGAYwILoOwBCQw85iQMV+4oOHYVN/jKfQblSJj9qxma9IDAk5PAoC9sQeVSc5MSsHE+Sc4+W40McpORdJt+g3Jm7+a4njA3aY3xoR/581JSyZTv/lVDlINDn9VoVnKF5WJsfenbfMzlCZu+uulvgQHInIObbMEShi7F0y/EJrE0GHC4fck01vmig99N/zUY5+NQ/AZCap+Q4HO5ZF09OegE706wi+TzutW6l2Z+xW2cTum+j6a3hpPA5jFLcvxSaqHEAdKBNBJTF+sIykUoKlTeNYJDVos6TaFdyndR+9LVnl4g9LqeD5t267gWvWoFBiZfdEGXMwvvuNutmT9jY0YiHtYsNI+F+JkE6AGBBsaMdceDzYtguvhWdTQ+T3URPl2qkP/c4iPOlhJz8Cvu5zdbP+kaZ1lwp1W+EnCvPsiU9fAhxEFvk+Iym+e/Njg9+3QU9LEFWeA9ST+8y+M=
