dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: BI0c/EjXHeVtHBJ7F9lDUVrC3AumTeTR7obrAHImRlvgSCCWgwsyQhRR1OBTGZyGDcRV98Jhwi0MgH++WcYl8zaOKZod/YTXY0ZOalgmoguv7KKEz7uMSHrlLaguxmEPP2/QYT6Ua3ACJa3TUDp4sMpZoY80YKMCxDzaz3nZ3a8edEolBB7BmF63lMIiInM31AVsr2u1f4XSVGCXX7V8DOB3bQdRMklr+HwH+ojHRhCLTbOZceHXm08eJWxmEoCnCaS78SYRr/ZAl8PYPrEVuZCcxN9eDe/9gzksZOrQK+lLR6E68sp39cz25PtjuVk7v6fbXosxae84g0eguCIaW5amKmJ0wr4ATdLIuaNpjVoLPVHWwfZ6jy9LKtFxTt7VLnElY0HtH3TPcZDi3XGbIGACnmcWrB8PXWsqNUbN6c+QhRrr5zDyYz8eqqQC3FTFFmZDNrunwC7fAkrmL+9bB7uaWyfzwGJbJhFxg/SQroZKHxxUwkkvxIE+DJu8UfrK20avc7FhbU0et7osG002QwU/smo7eJqwO6MUMTwiTvGuXkOQ4va8CfMgflmMKITAC38O2sU2zAOIDYXUbTWEMvlxVxkRrwsDjLBuGsyn8zJbN7ZhU9i0LF4TiVwE415ZAsZPVjlUsrw52b7kvOGZ8syTkyhB5pWl0gGJYZsZeGw=
