dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: "iwIe4wv0E6xGyCqcwCzBDx+sp4FFnp3R4LJ7V/lkhunnRu6iwHAUNEwerqFBpPatllzqatKoZaCq4EPruW3ebCkbjOFDXsmOCdCpaCsRvBUG8QzKH3Z/HqoYVu6JitSetQyFDr9qdFTVYset4gGrXajbELtiotZ3UMD2EnYZd04IrGDqHml2BjEfiICMHZ9R0ytmhrpUJ1bySODBK9DKXT6PIsRs6M6QhZby2UAoKTDYM8YG5EfUicXDm5FWdbLpRR+iTL+qwwJ4BNpr84NOLAy/CqSIhRwI/I+BWlgPXdgPgbK8Ho7v3HqIEtKxCmZAq44RwUYngEm504Oqp9e1zSzMw30aT8+5knvoEN925ajFyE3CjRfNkueNJ88myrEsD5j8QCrGqL5gZiMquSVovBbgpZqADPduvAe5/2DtKgFX/nDHcYcIfBbDmBDoOupVx2oPp49CyjTUrSagja8LTZVdhXg4+ze8Zx2bq9nAtUpNQdqsZjYaLo2xHiFW/85kQrwxMADaWrpIX1M1tpgz0uIOE0uamrF0K474NUQCqlJQ3p/IR4lpBat8JWdeXwdHaPCCVgu1aWzVQ47wMUBe2EXgiAH6TPJT0xHufDOa0oEPBhoN8IZfdtk1va+fg+AvNw/XF+3icdQGQMsKnUPevZNaKNbitPSlbA6JvVH7iOU="

